"""Connector application: ConnectorService and the ports it talks through."""

from .dto import (
    HARVEST_ROLES,
    WRITE_ROLES,
    AuthenticatedActor,
    CatalogVersionNotFoundError,
    ConflictError,
    ConnectionFailedError,
    DataSourceNotFoundError,
    DeletionPreview,
    HarvestRunNotFoundError,
    HarvestStatus,
    JoinGraphView,
    LandedTable,
    PermissionDeniedError,
    ReharvestReport,
    RelationNotFoundError,
    RelationView,
    Role,
    SourceCredentials,
    SourceFieldDescriptor,
    SourceSummary,
    SourceTableDescriptor,
    UploadPreview,
    UploadRejectedError,
)
from .harvesting import HarvestDependencies, execute_harvest
from .ports import (
    CatalogRepository,
    Clock,
    CredentialCipher,
    DataSourceRepository,
    FileLandingZone,
    HarvestRunRepository,
    RelationRepository,
    SourceConnector,
)
from .service import ConnectorService
from .views import to_relation_view, to_status, to_summary

__all__ = [
    "HARVEST_ROLES",
    "WRITE_ROLES",
    "AuthenticatedActor",
    "CatalogRepository",
    "CatalogVersionNotFoundError",
    "Clock",
    "ConflictError",
    "ConnectionFailedError",
    "ConnectorService",
    "CredentialCipher",
    "DataSourceNotFoundError",
    "DataSourceRepository",
    "DeletionPreview",
    "FileLandingZone",
    "HarvestDependencies",
    "HarvestRunNotFoundError",
    "HarvestRunRepository",
    "HarvestStatus",
    "JoinGraphView",
    "LandedTable",
    "PermissionDeniedError",
    "ReharvestReport",
    "RelationNotFoundError",
    "RelationRepository",
    "RelationView",
    "Role",
    "SourceConnector",
    "SourceCredentials",
    "SourceFieldDescriptor",
    "SourceSummary",
    "SourceTableDescriptor",
    "UploadPreview",
    "UploadRejectedError",
    "execute_harvest",
    "to_relation_view",
    "to_status",
    "to_summary",
]
