"""Investigation domain."""

from .citation import (
    CitationFilter,
    CitationState,
    EvidenceCitation,
    Tombstone,
)
from .draft_finding import (
    Claim,
    ClaimKind,
    Contradiction,
    DraftFinding,
    DraftFindingError,
    RootCauseState,
)
from .erasure import (
    PRESERVED,
    DeletionCategory,
    ErasureError,
    ErasureOperation,
    ErasureProgress,
    EvidenceSurface,
    require_erasable,
)
from .model import (
    TERMINAL_STATUSES,
    ApprovalDecision,
    ApprovalReason,
    CompletionOutcome,
    DomainEvent,
    EvaluationDirective,
    EvidenceReference,
    FailureOutcome,
    Finding,
    HumanApproval,
    HumanApprovalStatus,
    Investigation,
    InvestigationStatus,
    InvestigationTransitionError,
    MetricComparison,
    RejectionReason,
    confidence_ceiling,
    directive_for_outcome,
)
from .publication import (
    PublicationCondition,
    PublicationDecision,
    evaluate_publication,
)

__all__ = [
    "ApprovalDecision",
    "ApprovalReason",
    "CitationFilter",
    "CitationState",
    "Claim",
    "ClaimKind",
    "CompletionOutcome",
    "Contradiction",
    "DomainEvent",
    "DraftFinding",
    "DraftFindingError",
    "DeletionCategory",
    "ErasureError",
    "ErasureOperation",
    "ErasureProgress",
    "EvaluationDirective",
    "EvidenceSurface",
    "EvidenceCitation",
    "EvidenceReference",
    "FailureOutcome",
    "Finding",
    "HumanApproval",
    "HumanApprovalStatus",
    "Investigation",
    "InvestigationStatus",
    "InvestigationTransitionError",
    "PRESERVED",
    "MetricComparison",
    "PublicationCondition",
    "PublicationDecision",
    "RejectionReason",
    "RootCauseState",
    "TERMINAL_STATUSES",
    "Tombstone",
    "confidence_ceiling",
    "directive_for_outcome",
    "evaluate_publication",
    "require_erasable",
]
